Repository AimRT/AimRT, pull requests merged in 2024-10, with the labels that each got.

#14 CI: Add GitHub Actions to test on multiple platforms (amd64, arm64, msvc)
  .github/workflows/Main.yml
  .github/workflows/build-msvc-workflow.yml
  .github/workflows/build-workflow.yml
  .github/workflows/cppcheck.yml
  .github/workflows/deploy-workflow.yml
  .github/workflows/release-workflow.yml
  .github/workflows/test-msvc-workflow.yml
  .github/workflows/test-workflow.yml
Labels: reviewed

#19 feat: add proxy for workflow
  .github/workflows/Main.yml
  .github/workflows/build-workflow.yml
  .github/workflows/deploy-workflow.yml
  .github/workflows/test-workflow.yml
  build.sh
  test.sh
Labels: reviewed

#20 CI : Add auto-upload for releases and refine PR labeling
  .github/workflows/Main.yml
Labels: ci ready

#24 build: add Windows specific compile option for ssize_t
  src/plugins/grpc_plugin/CMakeLists.txt
  src/plugins/grpc_plugin/grpc/message.h
Labels: ci ready

#23 build: reorganize CMake configuration to fix windows build by fetchcontent
  CMakeLists.txt
Labels: ci ready

#25 fix iceoryx plugin example
  document/sphinx-cn/tutorials/quick_start/build_from_source_windows.md
  src/examples/plugins/iceoryx_plugin/install/linux/bin/start_examples_plugins_iceoryx_plugin_ros2_chn_pub.sh
  src/examples/plugins/iceoryx_plugin/install/linux/bin/start_examples_plugins_iceoryx_plugin_ros2_chn_sub.sh
Labels: ci ready

#27 build: update download URLs for dependencies
  url_cn.bashrc
Labels: ci ready

#26 build: simplify Boost fetching logic
  cmake/GetBoost.cmake
Labels: ci ready

#28 feat: add aimrt_py benchmark publisher and subscriber applications
  document/sphinx-cn/release_notes/v0_9_0.md
  document/sphinx-cn/tutorials/examples/examples_py.md
  src/examples/cpp/pb_chn/module/benchmark_subscriber_module/benchmark_subscriber_module.cc
  src/examples/py/helloworld/README.md
  src/examples/py/parameter/README.md
  src/examples/py/pb_chn/README.md
  src/examples/py/pb_chn_bench/README.md
  src/examples/py/pb_chn_bench/benchmark_publisher_app.py
  src/examples/py/pb_chn_bench/benchmark_publisher_module.py
  src/examples/py/pb_chn_bench/benchmark_subscriber_app.py
  src/examples/py/pb_chn_bench/benchmark_subscriber_module.py
  src/examples/py/pb_chn_bench/build_py_pb_chn.sh
  src/examples/py/pb_chn_bench/cfg/benchmark_publisher_cfg.yaml
  src/examples/py/pb_chn_bench/cfg/benchmark_subscriber_cfg.yaml
  src/examples/py/pb_chn_bench/start_benchmark_publisher.sh
  src/examples/py/pb_chn_bench/start_benchmark_subscriber.sh
  src/examples/py/pb_rpc/README.md
  src/protocols/example/benchmark.proto
Labels: ci ready

#31 Zenoh update to 1.0.0.11
  CMakeLists.txt
  cmake/GetZenoh.cmake
  document/sphinx-cn/release_notes/v0_9_0.md
  document/sphinx-cn/tutorials/plugins/zenoh_plugin.md
  src/examples/plugins/zenoh_plugin/install/linux/bin/cfg/zenoh_native_config.json5
  src/plugins/zenoh_plugin/CMakeLists.txt
  src/plugins/zenoh_plugin/zenoh_manager.cc
  url_cn.bashrc
Labels: ci ready

#35 fix: add GIL for pybind11::bytes object accessing
  document/sphinx-cn/release_notes/v0_9_0.md
  src/runtime/python_runtime/export_channel.h
  src/runtime/python_runtime/export_rpc.h
Labels: ci ready

#38 v0.8.3 bugfix
  CMakeLists.txt
  VERSION
  document/sphinx-cn/release_notes/index.md
  document/sphinx-cn/release_notes/v0_8_2.md
  document/sphinx-cn/release_notes/v0_8_3.md
  src/plugins/grpc_plugin/CMakeLists.txt
  src/plugins/grpc_plugin/grpc/message.h
  src/runtime/python_runtime/export_channel.h
  src/runtime/python_runtime/export_rpc.h
Labels: ci ready

#34 run all examples of aimrt and generate the report
  document/sphinx-cn/release_notes/v0_9_0.md
  src/examples/utils/common.py
  src/examples/utils/example_items.py
  src/examples/utils/run_all_example.py
  src/examples/utils/run_all_example.sh
Labels: ci ready

#39 feat: add 'trans' command to aimrt_cli for converting aimrtbag to rosbag
  .github/workflows/Main.yml
  CMakeLists.txt
  document/sphinx-cn/tutorials/cli_tool/bagtrans_tool.md
  document/sphinx-cn/tutorials/index.md
  src/tools/CMakeLists.txt
  src/tools/bagtrans/CMakeLists.txt
  src/tools/bagtrans/MANIFEST.in
  src/tools/bagtrans/bagtrans/__init__.py
  src/tools/bagtrans/bagtrans/bagtrans.spec
  src/tools/bagtrans/bagtrans/command/__init__.py
  src/tools/bagtrans/bagtrans/command/trans_command.py
  src/tools/bagtrans/bagtrans/main.py
  src/tools/bagtrans/bagtrans/requirements.txt
  src/tools/bagtrans/bagtrans/trans/__init__.py
  src/tools/bagtrans/bagtrans/trans/rosbag_trans.py
  src/tools/bagtrans/setup.py
Labels: ci ready

#43 build: enable position-independent code
  CMakeLists.txt
Labels: ci

#44 feat: enhance aimrt_py channel with ctx functionality
  document/sphinx-cn/release_notes/v0_9_0.md
  src/examples/py/helloworld/examples_py_helloworld_registration_mode.py
  src/examples/py/pb_chn/examples_py_pb_chn_publisher_app.py
  src/examples/py/pb_chn/examples_py_pb_chn_subscriber_app.py
  src/examples/py/pb_rpc/examples_py_pb_rpc_client_app.py
  src/examples/utils/run_all_example.py
  src/runtime/python_runtime/__init__.py
  src/runtime/python_runtime/aimrt_py_pb_chn.py
  src/runtime/python_runtime/export_channel.h
  src/runtime/python_runtime/python_runtime_main.cc
Labels: ci

#48 feat: enhance aimrt_py rpc context handling and method overloads
  src/runtime/python_runtime/export_rpc.h
  src/runtime/python_runtime/python_runtime_main.cc
  src/tools/protoc_plugin_py_gen_aimrt_py_rpc/protoc_plugin_py_gen_aimrt_py_rpc.py
Labels: ci

#46 Ros2 plugin custom naming
  document/sphinx-cn/tutorials/plugins/ros2_plugin.md
  src/plugins/ros2_plugin/ros2_rpc_backend.cc
  src/plugins/ros2_plugin/ros2_rpc_backend.h
  src/plugins/ros2_plugin/ros2_rpc_backend_test.cc
  src/runtime/core/util/yaml_tools.cc
Labels: ci

#49 fix: bagtrans options bugs
  CMakeLists.txt
  build.bat
  build.sh
  document/sphinx-cn/release_notes/v0_9_0.md
  document/sphinx-cn/tutorials/cli_tool/bagtrans_tool.md
  document/sphinx-cn/tutorials/cli_tool/cli_tool.md
  src/tools/bagtrans/CMakeLists.txt
  src/tools/bagtrans/bagtrans/requirements.txt
  src/tools/bagtrans/setup.py
  test.bat
  test.sh
Labels: ci

#61 Refactor coroutine request handling and ensure unique client keys
  src/common/net/asio_http_cli.h
Labels: ci

#66 fix: misc adjustments
  CMakeLists.txt
  cmake/GetAsio.cmake
  cmake/GetTBB.cmake
  cmake/GetYamlCpp.cmake
  document/doxygen/build.bat
  document/sphinx-cn/release_notes/v0_9_0.md
  document/sphinx-cn/tutorials/interface_cpp/channel.md
  document/sphinx-cn/tutorials/interface_cpp/rpc.md
  document/sphinx-cn/tutorials/quick_start/installation_cpp.md
  src/common/net/CMakeLists.txt
  src/interface/aimrt_module_cpp_interface/CMakeLists.txt
  src/plugins/grpc_plugin/CMakeLists.txt
  src/protocols/CMakeLists.txt
  src/protocols/geometry/CMakeLists.txt
  src/protocols/sensor/joint.proto
  src/protocols/visualization/CMakeLists.txt
  src/runtime/core/CMakeLists.txt
  src/runtime/core/module/module_manager.cc
  src/tools/CMakeLists.txt
  src/tools/aimrt_cli/aimrt_cli/templates/workspace/ws_CMakeLists.txt.jinja2
  src/tools/package_aimrt_py/CMakeLists.txt
Labels: ci

#57 log format
  document/sphinx-cn/tutorials/cfg/log.md
  src/common/util/time_util.h
  src/examples/cpp/logger/README.md
  src/examples/cpp/logger/install/linux/bin/cfg/examples_cpp_logger_cfg.yaml
  src/runtime/core/logger/console_logger_backend.cc
  src/runtime/core/logger/console_logger_backend.h
  src/runtime/core/logger/formatter.h
  src/runtime/core/logger/formatter_test.cc
  src/runtime/core/logger/rotate_file_logger_backend.cc
  src/runtime/core/logger/rotate_file_logger_backend.h
Labels: ci

#68 refactor(tools): Restructure bagtrans tool and integrate into aimrt_cli
  CMakeLists.txt
  build.bat
  build.sh
  document/sphinx-cn/release_notes/v0_9_0.md
  document/sphinx-cn/tutorials/cli_tool/bagtrans_tool.md
  document/sphinx-cn/tutorials/cli_tool/cli_tool.md
  src/protocols/CMakeLists.txt
  src/tools/CMakeLists.txt
  src/tools/aimrt_cli/aimrt_cli/command/gen_command.py
  src/tools/aimrt_cli/aimrt_cli/command/trans_command.py
  src/tools/aimrt_cli/aimrt_cli/main.py
  src/tools/aimrt_cli/aimrt_cli/trans/__init__.py
  src/tools/aimrt_cli/aimrt_cli/trans/rosbag_trans.py
  src/tools/bagtrans/CMakeLists.txt
  src/tools/bagtrans/MANIFEST.in
  src/tools/bagtrans/bagtrans/__init__.py
  src/tools/bagtrans/bagtrans/bagtrans.spec
  src/tools/bagtrans/bagtrans/command/__init__.py
  src/tools/bagtrans/bagtrans/main.py
  src/tools/bagtrans/bagtrans/requirements.txt
  src/tools/bagtrans/setup.py
  test.bat
  test.sh
Labels: quick-ci
